
CREATE TABLE countries (
  ISOYEAR VARCHAR(50) NOT NULL,
  country_name VARCHAR(50) NOT NULL,
  PRIMARY KEY (ISOYEAR)
);

CREATE TABLE HIV_cases (
   dyear int NOT NULL,
  woman_ratio FLOAT NOT NULL,
  ISOYEAR VARCHAR(50) NOT NULL,
  PRIMARY KEY (dyear, ISOYEAR),
  FOREIGN KEY (ISOYEAR) REFERENCES countries(ISOYEAR) ON DELETE CASCADE


);

CREATE TABLE HIV_funding (
dyear int NOT NULL,
  total_funding FLOAT NOT NULL,
  ISOYEAR VARCHAR(50) NOT NULL,
  PRIMARY KEY (dyear, ISOYEAR),
  FOREIGN KEY (ISOYEAR) REFERENCES countries(ISOYEAR) ON DELETE CASCADE
);

CREATE TABLE HIV_education (
  dyear int NOT NULL,
  total_knowledge_rate FLOAT NOT NULL,
  ISOYEAR VARCHAR(50) NOT NULL,
  PRIMARY KEY (dyear, ISOYEAR),
  FOREIGN KEY (ISOYEAR) REFERENCES countries(ISOYEAR) ON DELETE CASCADE
);

CREATE TABLE HIV_death (
dyear int NOT NULL,
  death_num FLOAT NOT NULL,
  ISOYEAR VARCHAR(50) NOT NULL,
  PRIMARY KEY (dyear, ISOYEAR),
  FOREIGN KEY (ISOYEAR) REFERENCES countries(ISOYEAR) ON DELETE CASCADE
); 


 
